version: '3.8'
services:
  ur3-ros2:
    build:
      context: .
      dockerfile: Dockerfile
    image: ur3-ros2
    container_name: ur3_ros2_demostation
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - ./workspace/custom_code:/workspace/custom_code
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    tty: true
    stdin_open: true
