joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    min_position: 1.0472    # 60 deg
    max_position: 3.4907    # 200 deg
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.6

  shoulder_lift_joint:
    has_position_limits: true
    min_position: -2.0944         # -120 deg
    max_position: 0.0000          # 0 deg
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.6

  elbow_joint:
    has_position_limits: true
    min_position: 0.0873          # 5 deg
    max_position: 2.9671          # 170 deg
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.6

  wrist_1_joint:
    has_position_limits: true
    min_position: -4.1888         # 120 deg - 360 deg
    max_position: 5.9341          # 340 deg
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.8

  wrist_2_joint:
    has_position_limits: true
    min_position: -2.6180         # -150 deg
    max_position: 0.3491          # 20 deg
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.8

  wrist_3_joint:
    has_position_limits: true
    min_position: 0.1745          # 10 deg
    max_position: 6.2832          # 360 deg
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0

